CREATE TABLE device_status (
  sn            VARCHAR(64) PRIMARY KEY,
  online        BOOLEAN NOT NULL DEFAULT FALSE,
  last_seen_at  DATETIME(3) NULL,
  last_lwt_at   DATETIME(3) NULL,
  updated_at    DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
