CREATE TABLE device_permissions (
  sn             VARCHAR(64) PRIMARY KEY,
  can_dispense   BOOLEAN NOT NULL DEFAULT FALSE,
  locked_reason  ENUM('NOT_INSTALLED','LOCKED','MANUAL') NULL,
  updated_at     DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
