CREATE TABLE device_specs (
  id           BIGINT PRIMARY KEY AUTO_INCREMENT,
  spec_id      VARCHAR(32) UNIQUE NOT NULL,
  model_code   VARCHAR(32) NOT NULL,
  name         VARCHAR(64) NOT NULL,
  price_cents  BIGINT NOT NULL,
  recommended  TINYINT(1) NOT NULL DEFAULT 0,
  monitor_line VARCHAR(128),
  features_json JSON NOT NULL,
  status       ENUM('ACTIVE','INACTIVE') NOT NULL DEFAULT 'ACTIVE',
  created_at   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
