CREATE TABLE invoices (
  id            BIGINT PRIMARY KEY AUTO_INCREMENT,
  order_id      BIGINT NOT NULL,
  status        ENUM('ISSUING','ISSUED') NOT NULL DEFAULT 'ISSUING',
  type          VARCHAR(32) NOT NULL DEFAULT 'VAT_SPECIAL_13',
  download_url  VARCHAR(512),
  created_at    DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at    DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_order (order_id)
);
