CREATE TABLE home_layout_pref (
  user_id     BIGINT PRIMARY KEY,
  active_role ENUM('CONSUMER','OWNER','PROMOTER') NOT NULL DEFAULT 'CONSUMER',
  updated_at  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_home_layout_user FOREIGN KEY (user_id) REFERENCES users(id)
);
